click-troc-php/src/Entity/Announce.php
<?php

namespace App\Entity;

use App\Core\Manager\AbstractRequestManager;
use App\Request\ServiceRequest;
use DateTime;

class Announce extends AbstractRequestManager
{
    protected $id;

    protected $title;

    protected $description;

    protected $type;

    protected $upload_name;

    protected $user_id;

    protected $community_id;

    protected $created_at;

    protected $updated_at;

    protected $author;

    protected $uev_value;

    protected $waiting_exchange = false;

    protected $was_exchanged = false;

    protected $proposal = [];

    protected $images = [];

    protected $sr;

    public function __construct($ORM = true, $datas = null)
    {
        parent::__construct();

        if($datas !== null) {
            foreach ($datas as $attribut => $value) {
                $method = 'set' . str_replace(' ', '', ucwords(str_replace('_', ' ', $attribut)));
                if (is_callable(array($this, $method))) {
                    $this->$method($value);
                }
            }
        }

        $this->sr = new ServiceRequest();
        $results = $this->sr->findImageByAnnounceId($this->getId());
        foreach ($results as $result) {
            $this->images[] = $result;
        }

        if($ORM) {
            $this->author = $this->getUr()->findUserByIdWithoutPassword($this->getUserId());
            $proposals = $this->getPr()->findByAnnounce($this->getId());
            foreach ($proposals as $proposal) {
                $this->proposal[] = $proposal;
            }
        }

    }

    public function __set($name, $value)
    {
        $method = 'set'.str_replace(' ', '', ucwords(str_replace('_', ' ', $name)));
        if (is_callable(array($this, $method))) {
            $this->$method($value);
        }
    }


    private static function getSetter(string $setterName) {
        return 'set'.ucfirst($setterName);
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param mixed $user_id
     * @return Announce
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCommunityId()
    {
        return $this->community_id;
    }

    /**
     * @param mixed $community_id
     * @return Announce
     */
    public function setCommunityId($community_id)
    {
        $this->community_id = $community_id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     * @return Announce
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     * @return Announce
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUploadName()
    {
        return $this->upload_name;
    }

    /**
     * @param mixed $upload_name
     */
    public function setUploadName($upload_name)
    {
        $this->upload_name = $upload_name;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return mixed
     */
    public function getUevValue()
    {
        return $this->uev_value;
    }

    /**
     * @param mixed $uev_value
     * @return Announce
     */
    public function setUevValue($uev_value)
    {
        $this->uev_value = (int)$uev_value;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getProposal()
    {
        return $this->proposal;
    }

    /**
     * @param mixed $proposal
     */
    public function setProposal($proposal)
    {
        $this->proposal = $proposal;
        return $this;
    }

    /**
     * @return array
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * @param array $images
     * @return Announce
     */
    public function setImages($images)
    {
        $this->images = $images;
        return $this;
    }

    /**
     * @return bool
     */
    public function isWaitingExchange()
    {
        return $this->waiting_exchange;
    }

    /**
     * @param bool $waiting_exchange
     * @return Announce
     */
    public function setWaitingExchange($waiting_exchange)
    {
        $this->waiting_exchange = $waiting_exchange;
        return $this;
    }


    /**
     * @return bool
     */
    public function isWasExchanged()
    {
        return $this->was_exchanged;
    }

    /**
     * @param bool $was_exchanged
     * @return Announce
     */
    public function setWasExchanged($was_exchanged)
    {
        $this->was_exchanged = $was_exchanged;
        return $this;
    }
}

click-troc-php/src/Entity/Message.php
<?php

namespace App\Entity;

use App\Request\AnnounceRequest;
use App\Request\MessageRequest;
use App\Request\UserRequest;

class Message
{
    protected $id;

    protected $id2;

    protected $title;

    protected $sender_id;

    protected $receiver_id;

    protected $message;

    protected $created_at;

    protected $sender_read;

    protected $receiver_read;

    protected $announce_id = null;

    protected $sender;

    protected $receiver;

    protected $friendship_id = null;

    protected $has_discussion;

    protected $has_alert;

    protected $has_proposal;

    protected $announce;

    protected $receiverReadLastMessage = false;

    private $ar;

    private $ur;

    private $mr;

    public function __construct($relations = true, $datas = null, $getReceiverRead = false)
    {
        if($datas !== null) {
            foreach ($datas as $attribut => $value) {
                $method = 'set' . str_replace(' ', '', ucwords(str_replace('_', ' ', $attribut)));
                if (is_callable(array($this, $method))) {
                    $this->$method($value);
                }
            }
        }

        if($relations) {
            $this->ur = new UserRequest();
            $this->ar = new AnnounceRequest();
            $this->setSender($this->ur->findUserByIdWithoutPassword($this->getSenderId()));
            $this->setReceiver($this->ur->findUserByIdWithoutPassword($this->getReceiverId()));
            if ($this->getAnnounceId()) {
                $this->setAnnounce($this->ar->getAnnounceById($this->getAnnounceId()));
            }
        }

        if ($getReceiverRead) {
            $this->mr = new MessageRequest();
            $result = $this->mr->getReceiverReadLast($this->getId2());
            $this->setReceiverReadLastMessage(boolval($result['receiver_read']));
        }
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Message
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getId2()
    {
        return $this->id2;
    }

    /**
     * @param mixed $id2
     * @return Message
     */
    public function setId2($id2)
    {
        $this->id2 = $id2;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     * @return Message
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSenderId()
    {
        return $this->sender_id;
    }

    /**
     * @param mixed $senderId
     * @return Message
     */
    public function setSenderId($senderId)
    {
        $this->sender_id = $senderId;
        return $this;
    }


    /**
     * @return mixed
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param mixed $message
     * @return Message
     */
    public function setMessage($message)
    {
        $this->message = $message;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     * @return Message
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSenderRead()
    {
        return $this->sender_read;
    }

    /**
     * @param mixed $sender_read
     * @return Message
     */
    public function setSenderRead($sender_read)
    {
        $this->sender_read = $sender_read;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getReceiverRead()
    {
        return $this->receiver_read;
    }

    /**
     * @param mixed $receiver_read
     * @return Message
     */
    public function setReceiverRead($receiver_read)
    {
        $this->receiver_read = $receiver_read;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAnnounceId()
    {
        return $this->announce_id;
    }

    /**
     * @param mixed $announce_id
     * @return Message
     */
    public function setAnnounceId($announce_id)
    {
        $this->announce_id = $announce_id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getReceiverId()
    {
        return $this->receiver_id;
    }

    /**
     * @param mixed $receiverId
     */
    public function setReceiverId($receiverId)
    {
        $this->receiver_id = $receiverId;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @param mixed $sender
     */
    public function setSender($sender)
    {
        $this->sender = $sender;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    /**
     * @param mixed $receiver
     */
    public function setReceiver($receiver)
    {
        $this->receiver = $receiver;
        return $this;

    }

    /**
     * @return mixed
     */
    public function getFriendshipId()
    {
        return $this->friendship_id;
    }

    /**
     * @param mixed $friendship_id
     * @return Message
     */
    public function setFriendshipId($friendship_id)
    {
        $this->friendship_id = $friendship_id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHasDiscussion()
    {
        return $this->has_discussion;
    }

    /**
     * @param mixed $has_discussion
     * @return Message
     */
    public function setHasDiscussion($has_discussion)
    {
        $this->has_discussion = $has_discussion;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHasAlert()
    {
        return $this->has_alert;
    }

    /**
     * @param mixed $has_alert
     * @return Message
     */
    public function setHasAlert($has_alert)
    {
        $this->has_alert = $has_alert;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHasProposal()
    {
        return $this->has_proposal;
    }

    /**
     * @param mixed $has_proposal
     * @return Message
     */
    public function setHasProposal($has_proposal)
    {
        $this->has_proposal = $has_proposal;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAnnounce()
    {
        return $this->announce;
    }

    /**
     * @param mixed $announce
     * @return Message
     */
    public function setAnnounce($announce)
    {
        $this->announce = $announce;
        return $this;
    }

    /**
     * @return bool
     */
    public function isReceiverReadLastMessage()
    {
        return $this->receiverReadLastMessage;
    }

    /**
     * @param bool $receiverReadLastMessage
     * @return Message
     */
    public function setReceiverReadLastMessage($receiverReadLastMessage)
    {
        $this->receiverReadLastMessage = $receiverReadLastMessage;
        return $this;
    }
}

click-troc-php/src/Entity/Proposal.php
<?php


namespace App\Entity;


use App\Request\UserRequest;

class Proposal
{

    protected $id;

    protected $user_id_proposal;

    protected $announce;

    protected $accepted_at;

    protected $rejected_at;

    protected $created_at;

    protected $user;

    protected $ur;

    public function __construct($datas = null)
    {
        if($datas !== null) {
            foreach ($datas as $attribut => $value) {
                $method = 'set' . str_replace(' ', '', ucwords(str_replace('_', ' ', $attribut)));
                if (is_callable(array($this, $method))) {
                    $this->$method($value);
                }
            }
        }

        if($this->getUserIdProposal()) {
            $this->ur = new UserRequest();
            $this->setUser($this->ur->findUserById($this->getUserIdProposal()));
        }
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Proposal
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUserIdProposal()
    {
        return $this->user_id_proposal;
    }

    /**
     * @param mixed $user_id_proposal
     * @return Proposal
     */
    public function setUserIdProposal($user_id_proposal)
    {
        $this->user_id_proposal = $user_id_proposal;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAnnounce()
    {
        return $this->announce;
    }

    /**
     * @param mixed $announce
     * @return Proposal
     */
    public function setAnnounce($announce)
    {
        $this->announce = $announce;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAcceptedAt()
    {
        return $this->accepted_at;
    }

    /**
     * @param mixed $accepted_at
     * @return Proposal
     */
    public function setAcceptedAt($accepted_at)
    {
        $this->accepted_at = $accepted_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRejectedAt()
    {
        return $this->rejected_at;
    }

    /**
     * @param mixed $rejected_at
     * @return Proposal
     */
    public function setRejectedAt($rejected_at)
    {
        $this->rejected_at = $rejected_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     * @return Proposal
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Proposal
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }
}

click-troc-php/templates/communitiesList.html.twig
{% extends 'layout.html.twig' %}
{% block wrapper %}
    <section class="block--search">
        <!--<div class="block--info">
            <span>Recherche pour troquer</span>
        </div>-->
        {{ communitary }}
        {% include '_partials/_searchMotor.html.twig' %}
    </section>
    <section class="block--last-announce">
        <div class="block--title">
            {% if cityName is defined and cityName is not null %}
                <span class="first" style="width: auto">Listes Communautés</span>
            <span class="second" style="width: auto"><h5>{{ cityName }}</h5></span>
                {% else %}
                    <span class="first" style="width: 30%">Listes </span>
                    <span class="second" style="width: 70%"><h5>Communautés</h5></span>
            {% endif %}
        </div>
        <div class="announce-wrap">
            <ul>
                {% for community in communities %}
                    <li>
                        <div class="background-gradiant-announce"></div>
                        <img src="/uploads/community/{{ community.images[0].uploadName }}">
                        <div class="announce-info">
                            <h3>{{ community.name }}</h3>
                            <p>{{ community.description }}</p>
                            <button class="btn-principal"><a href="/communaute/{{ community.id }}" style="text-decoration: none">Voir</a></button>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <nav class="pagination-container">
            <div class="pagination">
                <a class="pagination-newer" href="#">PREV</a>
                <span class="pagination-inner">
					<a href="#">1</a>
					<a class="pagination-active" href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">6</a>
				</span>
                <a class="pagination-older" href="#">NEXT</a>
            </div>
        </nav>
    </section>
{% endblock wrapper %}

click-troc-php/templates/community.html.twig
{% extends 'layout.html.twig' %}
{% block wrapper %}
    <div class="block--communities-header">

        <div class="community-template-imgslider">
            <i class="fas fa-arrow-left prev"></i>
            {% set i = 0 %}
            {% for image in community.images %}
                {% set i = i + 1 %}
                {% if i == 1 %}
                    <div id="community-img-{{ i }}" style="background: url('/uploads/community/{{ image.uploadName }}')"></div>
                {% else %}
                    <div id="community-img-{{ i }}" class="none" style="background: url('/uploads/community/{{ image.uploadName }}')"></div>
                {% endif %}
            {% endfor %}
            <i class="fas fa-arrow-right next"></i>
        </div>

    </div>

    <div class="block--communities-infos">
        <div class="block--title" style="width: 100%">
            <span class="first" style="padding: 0px 0; height: auto">{{ community.name }}</span>
        </div>
        <div class="block--comunities-statistics">
            <div class="community-template-infos">
                <h3 class="title-infos">Membres</h3>
            </div>
            <div class="community-template-infos">
                <h3 class="title-infos">Annonces</h3>
            </div>
            <div class="community-template-infos">
                <h3 class="title-infos">Localisation</h3>
            </div>

            <div class="community-template-values">
                <p class="members-values">123</p>
            </div>
            <div class="community-template-values">
                <p class="announces-values">{{ announces | length }}</p>
            </div>
            <div class="community-template-values">
                <p class="location-values">{{ city.name }}</p>
            </div>
        </div>
        <div class="community-template-actions">
            {% if session.User %}
                {% if isAMember %}
                    <button class="btn-principal text-actions" id="add-announce-action" style="text-decoration: none;" href=""><a href="/communaute/{{ community.id }}/ajout-annonce">Ajouter annonce</a></button>
                    {% if community.admin != session.User.id %}
                    <button onclick="joinCommunityActionAjax({{ request.attributes.idCommunity }})" class="btn-principal text-actions" id="join-community-action" style="text-decoration: none; display: none;" href="">Rejoindre</button>
                    <button class="btn-principal text-actions" style="text-decoration: none;" href="">Contacter</button>
                    <button onclick="leaveCommunityActionAjax({{ request.attributes.idCommunity }})" class="btn-principal btn-principal-red text-actions" id="leave-community-action" style="text-decoration: none;" href="">Quitter</button>
                        {% endif %}
                    {% if community.admin == session.User.id %} <button class="btn-principal text-actions" id="add-admin-community" style="text-decoration: none;"><a href="/communaute/{{ community.id }}/admin">Gérer la communauté</a></button>{% endif %}

                {% else %}
                    <button onclick="joinCommunityActionAjax({{ request.attributes.idCommunity }})" class="btn-principal text-actions" id="join-community-action" style="text-decoration: none;" href="">Rejoindre</button>
                    <button class="btn-principal text-actions" id="add-announce-action" style="text-decoration: none; display:none;"><a href="/communaute/{{ community.id }}/ajout-annonce">Ajouter annonce</a></button>
                    {% if community.admin != session.User.id %}
                        <button class="btn-principal text-actions" style="text-decoration: none;" href="">Contacter</button>
                        <button onclick="leaveCommunityActionAjax({{ request.attributes.idCommunity }})" class="btn-principal btn-principal-red text-actions" id="leave-community-action" style="text-decoration: none; display: none;">Quitter</button>
                    {% endif %}
                {% endif %}

            {% else %}
                <p style="margin-top: 20px">Vous devez être <a style="color: #2c3e50; cursor: pointer" href="{{ router.generateUri('connexion.route') }}">connecté</a> pour rejoindre une communauté</p>
            {% endif %}
        </div>
    </div>
    <div class="block--community-last-announce">
        <div class="block--title">
            <span class="first">Dernières</span>
            <span class="second"><h5>annonces</h5></span>
        </div>
        <div class="community-announce-wrap">
            {% if announces is not empty %}
                <ul>
                {% for announce in announces %}
                <li>
                    <div class="background-gradiant-community-announce" onclick="redirectionToAnnounce({{ community.id }}, {{ announce.id }})"></div>
                    <img style="transform: translateY(-50%);" src="/uploads/announce/{{ announce.images[0].uploadName }}">
                    <div class="community-announce-info" onclick="redirectionToAnnounce({{ community.id }}, {{ announce.id }})">
                        <h3>{{ announce.title }}</h3>
                        <div class="community-announce-additional-info">
                            <div class="info-date">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                                {{ announce.createdAt|date('d/m/Y') }}
                            </div>
                            <div class="info-time">
                                <i class="far fa-clock"></i>
                                {{ announce.type }}
                            </div>
                            <div class="info-currency">
                                <i class="fas fa-money-bill" aria-hidden="true"></i>
                                {{ announce.uevValue }}
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <button style="margin: 0 auto; display: block;" class="btn-principal">Voir toutes les annonces</button>
            {% else  %}
                <p> Il n'y a pour le moment aucun annonce sur cette communauté</p>
            {% endif %}
        </div>
    </div>
    <div class="block--community-members" style="margin-top: 40px;">
        <div class="block--title" style="padding-top: 0px">
            <span class="first">Membres</span>
        </div>
        {% if community.members is not empty and community.members is not null %}
            <div class="members-list">
                {% for member in community.members %}
                    {% if member.id == community.admin %}
                        <div class="admin-community">
                            <h5 class="admin-community-status"> Administrateur</h5>
                            <div class="member-element" style="background:linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.45)), url('/uploads/avatar/{{ member.avatar[0].uploadName }}')">
                                {% if member.id == session.User.id %}
                                    <h5><a style="text-decoration: none; color: white" href="{{ router.generateUri('profil.user') }}">{{ member.username }}</a></h5>
                                {% else %}
                                    <h5><a style="text-decoration: none; color: white" href="{{ router.generateUri('show.profil.user', {'idUser' : member.id}) }}">{{ member.username }}</a></h5>
                                {% endif %}
                            </div>
                        </div>
                    {% else %}
                    <div class="member-element" style="background:linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.45)), url('/uploads/avatar/{{ member.avatar[0].uploadName }}')">
                        {% if member.id == session.User.id %}
                            <h5><a style="text-decoration: none; color: white" href="{{ router.generateUri('profil.user') }}">{{ member.username }}</a></h5>
                        {% else %}
                            <h5><a style="text-decoration: none; color: white" href="{{ router.generateUri('show.profil.user', {'idUser' : member.id}) }}">{{ member.username }}</a></h5>
                        {% endif %}
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun amis</p>
        {% endif %}
    </div>
{% endblock wrapper %}

click-troc-php/templates/showPrivateMessage.html.twig
{% extends 'layout.html.twig' %}
{% block wrapper %}
    <div class="block--message-box">
        <div class="block--title">
            <span class="first">Ma boite de </span>
            <span class="second">Réception</span>
        </div>
        <div class="private-message-list-show">
            <h3 id="private-announce-title">{{ messages[0].title }}</h3>

            <ul class="message-list-content-show" style="overflow: scroll; padding-top: 10px; max-height: 300px">
                {% for message in messages %}
                    {% if message.sender.id == session.User.id and message.hasProposal == false%}
                        <li class="message-list-element-show-right">
                            <div class="right-box-show">
                                <h5 class="right-message-title">Vous</h5>
                                <span class="right-date-message">{{ message.createdAt |date('d/m/Y') }}</span>
                                <p class="right-message-message-send">{{ message.message }}</p>
                            </div>
                        </li>
                    {% elseif message.hasProposal %}
                        <li class="message-list-element-show-left">
                            <div class="right-box-show" style="background: rgb(238,246,255)">
                                <span class="right-date-message" style="color: rgba(22, 22, 22, 1)">{{ message.createdAt |date('d/m/Y') }}</span>
                                <p class="right-message-message-send" style="color: rgba(22, 22, 22, 1)">{{ message.message }}</p>
                                <br/>
                                {% if message.announce.userId == session.User.id and proposal.acceptedAt is null%}
                                    <p class="right-message-message-send" style="margin-bottom: 10px; color: rgba(22, 22, 22, 1)">Cliquez sur l'annonce pour gérer les propositions</p>
                                    <div class="message-action-zone" style="margin-bottom: 20px;">
                                        <a class="btn-principal" style="text-decoration: none" href="{{ router.generateUri('show.announce', {'idCommunity' : message.announce.communityId, 'idAnnounce' : message.announce.id}) }}">Gérer propositions</a>
                                    </div>
                                {% endif %}
                            </div>
                        </li>
                    {% else %}
                        <li class="message-list-element-show-left">
                            <div class="left-box-show">
                                <h5 class="left-message-title">{{ message.sender.username }}</h5>
                                <span class="left-date-message">{{ message.createdAt |date('d/m/Y') }}</span>
                                <p class="left-message-message-send">{{ message.message }}</p>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="form-container">
        <form enctype="multipart/form-data" action="{{ router.generateUri("check.answer.message.announce", {'idMessage': messages[0].id|number_format}) }}" class="add-community-form" id="submitForm" method="post">
            <label for="label-anim" class="label-anim">
                <textarea type="text" name="message" placeholder="&nbsp;" value="{{ user.firstName }}"></textarea>
                <span class="label">Message</span>
                <span class="border"></span>
            </label>
            {% if messages[0].announce.userId != session.User.id and message[0].announceId is not null or proposal.userIdProposal == session.User.id %}
            <br/>
            <div class="checkbox-proposal" style="text-align: center">
                <input type="checkbox" id="makeProposal" name="makeProposal">
                <label for="makeProposal">Indiquer vouloir l'objet de l'annonce(échange/don/service)</label>
            </div>
            {% endif %}
            <br/>
            <div class="action-zone-content">
                <button class="btn-principal" type="submit">Envoyer</button>
                <button class="btn-principal btn-principal-red" type="button">Annuler</button>
            </div>
        </form>
    </div>
    <div class="clear-fix"></div>
    <script>
        {# automatically scroll in div#}
        var messageContent    = $('.message-list-content-show');
        var height = messageContent[0].scrollHeight;
        messageContent.scrollTop(height);
    </script>
{% endblock wrapper %}